// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto_src/bill.proto

package bill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiRequestEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppId      uint32 `protobuf:"varint,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                //app_id
	RequestId  string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`     //请求ID
	CreateTime uint64 `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` //时间戳，毫秒
	// Types that are assignable to TestOneof:
	//	*ApiRequestEvent_Name
	//	*ApiRequestEvent_Id
	TestOneof isApiRequestEvent_TestOneof `protobuf_oneof:"test_oneof"`
}

func (x *ApiRequestEvent) Reset() {
	*x = ApiRequestEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_src_bill_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApiRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiRequestEvent) ProtoMessage() {}

func (x *ApiRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_src_bill_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiRequestEvent.ProtoReflect.Descriptor instead.
func (*ApiRequestEvent) Descriptor() ([]byte, []int) {
	return file_proto_src_bill_proto_rawDescGZIP(), []int{0}
}

func (x *ApiRequestEvent) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ApiRequestEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ApiRequestEvent) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (m *ApiRequestEvent) GetTestOneof() isApiRequestEvent_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (x *ApiRequestEvent) GetName() string {
	if x, ok := x.GetTestOneof().(*ApiRequestEvent_Name); ok {
		return x.Name
	}
	return ""
}

func (x *ApiRequestEvent) GetId() uint32 {
	if x, ok := x.GetTestOneof().(*ApiRequestEvent_Id); ok {
		return x.Id
	}
	return 0
}

type isApiRequestEvent_TestOneof interface {
	isApiRequestEvent_TestOneof()
}

type ApiRequestEvent_Name struct {
	Name string `protobuf:"bytes,4,opt,name=name,proto3,oneof"`
}

type ApiRequestEvent_Id struct {
	Id uint32 `protobuf:"varint,5,opt,name=id,proto3,oneof"`
}

func (*ApiRequestEvent_Name) isApiRequestEvent_TestOneof() {}

func (*ApiRequestEvent_Id) isApiRequestEvent_TestOneof() {}

var File_proto_src_bill_proto protoreflect.FileDescriptor

var file_proto_src_bill_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x72, 0x63, 0x2f, 0x62, 0x69, 0x6c, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x62, 0x69, 0x6c, 0x6c, 0x22, 0x9e, 0x01, 0x0a,
	0x0f, 0x41, 0x70, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x42,
	0x0c, 0x0a, 0x0a, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x10, 0x5a,
	0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x72, 0x63, 0x2f, 0x62, 0x69, 0x6c, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_src_bill_proto_rawDescOnce sync.Once
	file_proto_src_bill_proto_rawDescData = file_proto_src_bill_proto_rawDesc
)

func file_proto_src_bill_proto_rawDescGZIP() []byte {
	file_proto_src_bill_proto_rawDescOnce.Do(func() {
		file_proto_src_bill_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_src_bill_proto_rawDescData)
	})
	return file_proto_src_bill_proto_rawDescData
}

var file_proto_src_bill_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_src_bill_proto_goTypes = []interface{}{
	(*ApiRequestEvent)(nil), // 0: bill.ApiRequestEvent
}
var file_proto_src_bill_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_src_bill_proto_init() }
func file_proto_src_bill_proto_init() {
	if File_proto_src_bill_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_src_bill_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApiRequestEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_src_bill_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ApiRequestEvent_Name)(nil),
		(*ApiRequestEvent_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_src_bill_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_src_bill_proto_goTypes,
		DependencyIndexes: file_proto_src_bill_proto_depIdxs,
		MessageInfos:      file_proto_src_bill_proto_msgTypes,
	}.Build()
	File_proto_src_bill_proto = out.File
	file_proto_src_bill_proto_rawDesc = nil
	file_proto_src_bill_proto_goTypes = nil
	file_proto_src_bill_proto_depIdxs = nil
}
